name: append-new-recipe

on: [push, pull_request, workflow_dispatch]

jobs:
  append-new-recipe:
    runs-on: ubuntu-latest
    env:
      path: homework/append-new-recipe/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ctest -V